# This file is auto-generated by generate_autocomplete.py

AUTOCOMPLETE = {
    "convert": {
        "array": [
            "average",
            "order",
        ],
        "bmp": [
            "average",
            "header_size",
            "sample_size",
        ],
        "qam": [
            "sample_rate",
            "carrier_frequency",
        ],
    },
    "edit": {
        "split_channels": [
            "mode",
            "channel",
        ],
    },
    "process": {
        "delay": [
            "pitch",
            "rt",
            "feedback",
            "pingpong",
            "lt",
            "mix",
        ],
        "distortion": [
            "gain",
            "kind",
        ],
    },
}
