# This file is auto-generated by generate_autocomplete.py

AUTOCOMPLETE = {
    "convert": {
        "array": [
            "average",
            "order",
        ],
        "bmp": [
            "average",
            "header_size",
            "sample_size",
        ],
        "qam": [
            "carrier_frequency",
            "sample_rate",
        ],
    },
    "edit": {
        "blur-c": [
            "radius",
        ],
        "blur-g": [
            "radius",
        ],
        "dither": [
            "palette",
        ],
        "exposure": [
            "stops",
        ],
        "extract_channel": [
            "channel",
            "mode",
        ],
        "film-grain": [
            "amount",
            "monochrome",
            "seed",
            "size",
        ],
    },
    "process": {
        "delay": [
            "feedback",
            "lt",
            "mix",
            "pingpong",
            "pitch",
            "rt",
        ],
        "distortion": [
            "gain",
            "kind",
        ],
    },
}
