# This file is auto-generated by generate_autocomplete.py

AUTOCOMPLETE = {
    "convert": {
        "array": [
            "order",
            "average",
        ],
        "bmp": [
            "sample_size",
            "header_size",
            "average",
        ],
        "qam": [
            "carrier_frequency",
            "sample_rate",
        ],
    },
    "edit": {
        "extract_channel": [
            "channel",
            "mode",
        ],
    },
    "process": {
        "delay": [
            "rt",
            "pitch",
            "mix",
            "pingpong",
            "feedback",
            "lt",
        ],
        "distortion": [
            "gain",
            "kind",
        ],
    },
}
